---
- name: ensure aide is the latest version 
  apt: name=aide update_cache=yes
- name: write our aide config
  copy: src=aide.conf dest=/etc/aide/aide.conf
- name: write our aide default config
  copy: src=aide dest=/etc/default/aide
- name: setup aide wrapper
  command: /usr/bin/aide.wrapper -D creates=/var/lib/aide/aide.db
- name: initalise aide
  command: /usr/sbin/aideinit creates=/var/lib/aide/aide.db
- name: fireoff the cronjob
  command: /etc/cron.daily/aide creates=/var/lib/aide/aide.db